# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80761ebc63d499634b0f3e6af77cbefae4ffa869c45a660e084b1ae2b8ed13852e04692abb9cbb41b0ef8b76b96378a6234dd91e83099c99754104341bd89b25

test:
  secret_key_base: deb037e375b127884f6418388a6a04f9b3abaa0272da12ab81bc83c057ca805b986c07adf8bf8942aded368bca7ab7720f0431b869cca2885ad031b6c70f24a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
